/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.service;

public class App {
    public static void main(String[] args) {
        System.out.println("Hello, Gradle!");
        System.out.println("Hello, Gradle2!");
        System.out.println("Hello, Gradle3!");
        System.out.println("Hello, Gradle4!");
    }
}
